services:
  workspace:
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_EXTERNAL_URL: jdbc:postgresql://postgres:5432/waste_app
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_USERNAME: waste_app
    volumes:
      - ..:/workspaces/waste-app:cached

  postgres:
    image: postgres:17.10-bookworm@sha256:4f736ae292687621d4dbe0d499ffd024a36bd2ee7d8ca6f2ccd4c800f047b394
    environment:
      POSTGRES_DB: waste_app
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: waste_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waste_app -d waste_app"]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - waste-app-postgres:/var/lib/postgresql/data

volumes:
  waste-app-postgres:
